// Mocks generated by Mockito 5.4.4 from annotations
// in journal_app/test/support/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:convert' as _i16;
import 'dart:typed_data' as _i17;
import 'dart:ui' as _i4;

import 'package:auto_route/auto_route.dart' as _i15;
import 'package:flutter/material.dart' as _i5;
import 'package:http/http.dart' as _i2;
import 'package:journal_app/features/authentication/services/auth_service.dart' as _i22;
import 'package:journal_app/features/authentication/services/image_service.dart' as _i21;
import 'package:journal_app/features/authentication/services/token_service.dart' as _i19;
import 'package:journal_app/features/authentication/services/user_service.dart' as _i7;
import 'package:journal_app/features/entry/models/updated_entry.dart' as _i13;
import 'package:journal_app/features/journal/services/journal_entry_service.dart' as _i10;
import 'package:journal_app/features/mood/models/mood.dart' as _i3;
import 'package:journal_app/features/shared/abstractions/base_user.dart' as _i9;
import 'package:journal_app/features/shared/models/journal_entry.dart' as _i11;
import 'package:journal_app/features/shared/models/new_entry.dart' as _i12;
import 'package:journal_app/features/shared/services/mood_service.dart' as _i18;
import 'package:journal_app/features/shared/services/time_service.dart' as _i20;
import 'package:journal_app/features/shared/services/toast_service.dart' as _i23;
import 'package:journal_app/features/shared/utilities/popup_parameters.dart' as _i24;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

import 'test_helpers.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_1 extends _i1.SmartFake implements _i2.StreamedResponse {
  _FakeStreamedResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMood_2 extends _i1.SmartFake implements _i3.Mood {
  _FakeMood_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeColor_3 extends _i1.SmartFake implements _i4.Color {
  _FakeColor_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeImageProvider_4<T extends Object> extends _i1.SmartFake implements _i5.ImageProvider<T> {
  _FakeImageProvider_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_5<T1> extends _i1.SmartFake implements _i6.Future<T1> {
  _FakeFuture_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i7.UserService {
  @override
  String get bearerPrefix => (super.noSuchMethod(
        Invocation.getter(#bearerPrefix),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#bearerPrefix),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#bearerPrefix),
        ),
      ) as String);

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
        returnValueForMissingStub: <String, String>{},
      ) as Map<String, String>);

  @override
  String get host => (super.noSuchMethod(
        Invocation.getter(#host),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#host),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#host),
        ),
      ) as String);

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.Future<void> createTempUser() => (super.noSuchMethod(
        Invocation.method(
          #createTempUser,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void setCurrentUser(Map<String, dynamic>? responseBody) => super.noSuchMethod(
        Invocation.method(
          #setCurrentUser,
          [responseBody],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i2.Response> updateUserInfo(_i9.BaseUser? updatedUser) => (super.noSuchMethod(
        Invocation.method(
          #updateUserInfo,
          [updatedUser],
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #updateUserInfo,
            [updatedUser],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #updateUserInfo,
            [updatedUser],
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  void clearUserData() => super.noSuchMethod(
        Invocation.method(
          #clearUserData,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearTempUserData() => super.noSuchMethod(
        Invocation.method(
          #clearTempUserData,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTempUserFirstName(String? val) => super.noSuchMethod(
        Invocation.method(
          #setTempUserFirstName,
          [val],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTempUserLastName(String? val) => super.noSuchMethod(
        Invocation.method(
          #setTempUserLastName,
          [val],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTempUserEmail(String? val) => super.noSuchMethod(
        Invocation.method(
          #setTempUserEmail,
          [val],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTempUserPhoneNumber(String? val) => super.noSuchMethod(
        Invocation.method(
          #setTempUserPhoneNumber,
          [val],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTempUserPassword(String? val) => super.noSuchMethod(
        Invocation.method(
          #setTempUserPassword,
          [val],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i2.Response> get(
    String? endpoint, {
    String? tempHost,
    Map<String, String>? extraHeaders,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
          {
            #tempHost: tempHost,
            #extraHeaders: extraHeaders,
          },
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #get,
            [endpoint],
            {
              #tempHost: tempHost,
              #extraHeaders: extraHeaders,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #get,
            [endpoint],
            {
              #tempHost: tempHost,
              #extraHeaders: extraHeaders,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> post(
    String? endpoint, {
    required dynamic body,
    String? tempHost,
    Map<String, String>? baseHeaders,
    Map<String, String>? extraHeaders,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [endpoint],
          {
            #body: body,
            #tempHost: tempHost,
            #baseHeaders: baseHeaders,
            #extraHeaders: extraHeaders,
          },
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #post,
            [endpoint],
            {
              #body: body,
              #tempHost: tempHost,
              #baseHeaders: baseHeaders,
              #extraHeaders: extraHeaders,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #post,
            [endpoint],
            {
              #body: body,
              #tempHost: tempHost,
              #baseHeaders: baseHeaders,
              #extraHeaders: extraHeaders,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> put(
    String? endpoint, {
    required dynamic body,
    String? tempHost,
    Map<String, String>? extraHeaders,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [endpoint],
          {
            #body: body,
            #tempHost: tempHost,
            #extraHeaders: extraHeaders,
          },
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #put,
            [endpoint],
            {
              #body: body,
              #tempHost: tempHost,
              #extraHeaders: extraHeaders,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #put,
            [endpoint],
            {
              #body: body,
              #tempHost: tempHost,
              #extraHeaders: extraHeaders,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> delete(
    String? endpoint, {
    dynamic body,
    String? tempHost,
    Map<String, String>? extraHeaders,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [endpoint],
          {
            #body: body,
            #tempHost: tempHost,
            #extraHeaders: extraHeaders,
          },
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #delete,
            [endpoint],
            {
              #body: body,
              #tempHost: tempHost,
              #extraHeaders: extraHeaders,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #delete,
            [endpoint],
            {
              #body: body,
              #tempHost: tempHost,
              #extraHeaders: extraHeaders,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) => super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [JournalEntryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockJournalEntryService extends _i1.Mock implements _i10.JournalEntryService {
  @override
  List<_i11.JournalEntry> get journalEntries => (super.noSuchMethod(
        Invocation.getter(#journalEntries),
        returnValue: <_i11.JournalEntry>[],
        returnValueForMissingStub: <_i11.JournalEntry>[],
      ) as List<_i11.JournalEntry>);

  @override
  set journalEntries(List<_i11.JournalEntry>? _journalEntries) => super.noSuchMethod(
        Invocation.setter(
          #journalEntries,
          _journalEntries,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get bearerPrefix => (super.noSuchMethod(
        Invocation.getter(#bearerPrefix),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#bearerPrefix),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#bearerPrefix),
        ),
      ) as String);

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
        returnValueForMissingStub: <String, String>{},
      ) as Map<String, String>);

  @override
  String get host => (super.noSuchMethod(
        Invocation.getter(#host),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#host),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#host),
        ),
      ) as String);

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i6.Future<_i2.Response> getAllEntries() => (super.noSuchMethod(
        Invocation.method(
          #getAllEntries,
          [],
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #getAllEntries,
            [],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #getAllEntries,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> addEntry(_i12.NewEntry? newEntry) => (super.noSuchMethod(
        Invocation.method(
          #addEntry,
          [newEntry],
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #addEntry,
            [newEntry],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #addEntry,
            [newEntry],
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> updateEntry(_i13.UpdatedEntry? updatedEntry) => (super.noSuchMethod(
        Invocation.method(
          #updateEntry,
          [updatedEntry],
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #updateEntry,
            [updatedEntry],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #updateEntry,
            [updatedEntry],
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> deleteEntry(int? entryId) => (super.noSuchMethod(
        Invocation.method(
          #deleteEntry,
          [entryId],
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #deleteEntry,
            [entryId],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #deleteEntry,
            [entryId],
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> get(
    String? endpoint, {
    String? tempHost,
    Map<String, String>? extraHeaders,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
          {
            #tempHost: tempHost,
            #extraHeaders: extraHeaders,
          },
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #get,
            [endpoint],
            {
              #tempHost: tempHost,
              #extraHeaders: extraHeaders,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #get,
            [endpoint],
            {
              #tempHost: tempHost,
              #extraHeaders: extraHeaders,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> post(
    String? endpoint, {
    required dynamic body,
    String? tempHost,
    Map<String, String>? baseHeaders,
    Map<String, String>? extraHeaders,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [endpoint],
          {
            #body: body,
            #tempHost: tempHost,
            #baseHeaders: baseHeaders,
            #extraHeaders: extraHeaders,
          },
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #post,
            [endpoint],
            {
              #body: body,
              #tempHost: tempHost,
              #baseHeaders: baseHeaders,
              #extraHeaders: extraHeaders,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #post,
            [endpoint],
            {
              #body: body,
              #tempHost: tempHost,
              #baseHeaders: baseHeaders,
              #extraHeaders: extraHeaders,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> put(
    String? endpoint, {
    required dynamic body,
    String? tempHost,
    Map<String, String>? extraHeaders,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [endpoint],
          {
            #body: body,
            #tempHost: tempHost,
            #extraHeaders: extraHeaders,
          },
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #put,
            [endpoint],
            {
              #body: body,
              #tempHost: tempHost,
              #extraHeaders: extraHeaders,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #put,
            [endpoint],
            {
              #body: body,
              #tempHost: tempHost,
              #extraHeaders: extraHeaders,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> delete(
    String? endpoint, {
    dynamic body,
    String? tempHost,
    Map<String, String>? extraHeaders,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [endpoint],
          {
            #body: body,
            #tempHost: tempHost,
            #extraHeaders: extraHeaders,
          },
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #delete,
            [endpoint],
            {
              #body: body,
              #tempHost: tempHost,
              #extraHeaders: extraHeaders,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #delete,
            [endpoint],
            {
              #body: body,
              #tempHost: tempHost,
              #extraHeaders: extraHeaders,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) => super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MockRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppRouter extends _i1.Mock implements _i14.MockRouter {
  @override
  List<_i15.AutoRoute> get routes => (super.noSuchMethod(
        Invocation.getter(#routes),
        returnValue: <_i15.AutoRoute>[],
        returnValueForMissingStub: <_i15.AutoRoute>[],
      ) as List<_i15.AutoRoute>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i2.Client {
  @override
  _i6.Future<_i2.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i16.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i16.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i16.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i16.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
        returnValueForMissingStub: _i6.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<_i17.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i17.Uint8List>.value(_i17.Uint8List(0)),
        returnValueForMissingStub: _i6.Future<_i17.Uint8List>.value(_i17.Uint8List(0)),
      ) as _i6.Future<_i17.Uint8List>);

  @override
  _i6.Future<_i2.StreamedResponse> send(_i2.BaseRequest? request) => (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue: _i6.Future<_i2.StreamedResponse>.value(_FakeStreamedResponse_1(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.StreamedResponse>.value(_FakeStreamedResponse_1(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i6.Future<_i2.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MoodService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoodService extends _i1.Mock implements _i18.MoodService {
  @override
  List<MapEntry<String, ({_i4.Color color, double defaultSize, String imagePath})>> get moods => (super.noSuchMethod(
        Invocation.getter(#moods),
        returnValue: <MapEntry<String, ({_i4.Color color, double defaultSize, String imagePath})>>[],
        returnValueForMissingStub: <MapEntry<String, ({_i4.Color color, double defaultSize, String imagePath})>>[],
      ) as List<MapEntry<String, ({_i4.Color color, double defaultSize, String imagePath})>>);

  @override
  _i3.Mood createMoodByType(
    String? moodType, [
    double? imageSize,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMoodByType,
          [
            moodType,
            imageSize,
          ],
        ),
        returnValue: _FakeMood_2(
          this,
          Invocation.method(
            #createMoodByType,
            [
              moodType,
              imageSize,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeMood_2(
          this,
          Invocation.method(
            #createMoodByType,
            [
              moodType,
              imageSize,
            ],
          ),
        ),
      ) as _i3.Mood);

  @override
  _i4.Color getMoodColorByType(String? moodType) => (super.noSuchMethod(
        Invocation.method(
          #getMoodColorByType,
          [moodType],
        ),
        returnValue: _FakeColor_3(
          this,
          Invocation.method(
            #getMoodColorByType,
            [moodType],
          ),
        ),
        returnValueForMissingStub: _FakeColor_3(
          this,
          Invocation.method(
            #getMoodColorByType,
            [moodType],
          ),
        ),
      ) as _i4.Color);

  @override
  MapEntry<String, ({_i4.Color color, double defaultSize, String imagePath})> getMoodByIndex(int? index) => (super.noSuchMethod(
        Invocation.method(
          #getMoodByIndex,
          [index],
        ),
        returnValue: _i8.dummyValue<MapEntry<String, ({_i4.Color color, double defaultSize, String imagePath})>>(
          this,
          Invocation.method(
            #getMoodByIndex,
            [index],
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<MapEntry<String, ({_i4.Color color, double defaultSize, String imagePath})>>(
          this,
          Invocation.method(
            #getMoodByIndex,
            [index],
          ),
        ),
      ) as MapEntry<String, ({_i4.Color color, double defaultSize, String imagePath})>);
}

/// A class which mocks [TokenService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenService extends _i1.Mock implements _i19.TokenService {
  @override
  _i6.Future<void> saveTokenData(Map<String, dynamic>? responseBody) => (super.noSuchMethod(
        Invocation.method(
          #saveTokenData,
          [responseBody],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> saveAccessTokenToStorage(String? token) => (super.noSuchMethod(
        Invocation.method(
          #saveAccessTokenToStorage,
          [token],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String?> getAccessTokenFromStorage() => (super.noSuchMethod(
        Invocation.method(
          #getAccessTokenFromStorage,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
        returnValueForMissingStub: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<void> removeAccessTokenFromStorage() => (super.noSuchMethod(
        Invocation.method(
          #removeAccessTokenFromStorage,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [TimeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimeService extends _i1.Mock implements _i20.TimeService {
  @override
  String dayOfWeekByName([DateTime? dateTime]) => (super.noSuchMethod(
        Invocation.method(
          #dayOfWeekByName,
          [dateTime],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #dayOfWeekByName,
            [dateTime],
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #dayOfWeekByName,
            [dateTime],
          ),
        ),
      ) as String);

  @override
  String customDateString(
    String? pattern, [
    DateTime? dateTime,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #customDateString,
          [
            pattern,
            dateTime,
          ],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #customDateString,
            [
              pattern,
              dateTime,
            ],
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #customDateString,
            [
              pattern,
              dateTime,
            ],
          ),
        ),
      ) as String);

  @override
  String timeOfDay([DateTime? dateTime]) => (super.noSuchMethod(
        Invocation.method(
          #timeOfDay,
          [dateTime],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #timeOfDay,
            [dateTime],
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #timeOfDay,
            [dateTime],
          ),
        ),
      ) as String);

  @override
  String getStringFromDate(DateTime? dataTime) => (super.noSuchMethod(
        Invocation.method(
          #getStringFromDate,
          [dataTime],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #getStringFromDate,
            [dataTime],
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #getStringFromDate,
            [dataTime],
          ),
        ),
      ) as String);

  @override
  String getContinentalTime(DateTime? dateTime) => (super.noSuchMethod(
        Invocation.method(
          #getContinentalTime,
          [dateTime],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #getContinentalTime,
            [dateTime],
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #getContinentalTime,
            [dateTime],
          ),
        ),
      ) as String);
}

/// A class which mocks [ImageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageService extends _i1.Mock implements _i21.ImageService {
  @override
  _i5.ImageProvider<Object> get mindful01 => (super.noSuchMethod(
        Invocation.getter(#mindful01),
        returnValue: _FakeImageProvider_4<Object>(
          this,
          Invocation.getter(#mindful01),
        ),
        returnValueForMissingStub: _FakeImageProvider_4<Object>(
          this,
          Invocation.getter(#mindful01),
        ),
      ) as _i5.ImageProvider<Object>);

  @override
  set mindful01(_i5.ImageProvider<Object>? _mindful01) => super.noSuchMethod(
        Invocation.setter(
          #mindful01,
          _mindful01,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.ImageProvider<Object> get mindful02 => (super.noSuchMethod(
        Invocation.getter(#mindful02),
        returnValue: _FakeImageProvider_4<Object>(
          this,
          Invocation.getter(#mindful02),
        ),
        returnValueForMissingStub: _FakeImageProvider_4<Object>(
          this,
          Invocation.getter(#mindful02),
        ),
      ) as _i5.ImageProvider<Object>);

  @override
  set mindful02(_i5.ImageProvider<Object>? _mindful02) => super.noSuchMethod(
        Invocation.setter(
          #mindful02,
          _mindful02,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.ImageProvider<Object> get mindful03 => (super.noSuchMethod(
        Invocation.getter(#mindful03),
        returnValue: _FakeImageProvider_4<Object>(
          this,
          Invocation.getter(#mindful03),
        ),
        returnValueForMissingStub: _FakeImageProvider_4<Object>(
          this,
          Invocation.getter(#mindful03),
        ),
      ) as _i5.ImageProvider<Object>);

  @override
  set mindful03(_i5.ImageProvider<Object>? _mindful03) => super.noSuchMethod(
        Invocation.setter(
          #mindful03,
          _mindful03,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i6.Future<void> cacheImage(_i5.BuildContext? context) => (super.noSuchMethod(
        Invocation.method(
          #cacheImage,
          [context],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i5.ImageProvider<Object> getRandomMindfulImage() => (super.noSuchMethod(
        Invocation.method(
          #getRandomMindfulImage,
          [],
        ),
        returnValue: _FakeImageProvider_4<Object>(
          this,
          Invocation.method(
            #getRandomMindfulImage,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeImageProvider_4<Object>(
          this,
          Invocation.method(
            #getRandomMindfulImage,
            [],
          ),
        ),
      ) as _i5.ImageProvider<Object>);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) => super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i22.AuthService {
  @override
  bool get isLoggedIn => (super.noSuchMethod(
        Invocation.getter(#isLoggedIn),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get bearerPrefix => (super.noSuchMethod(
        Invocation.getter(#bearerPrefix),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#bearerPrefix),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#bearerPrefix),
        ),
      ) as String);

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
        returnValueForMissingStub: <String, String>{},
      ) as Map<String, String>);

  @override
  String get host => (super.noSuchMethod(
        Invocation.getter(#host),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#host),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#host),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.Future<_i2.Response> register({required _i9.BaseUser? user}) => (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {#user: user},
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #register,
            [],
            {#user: user},
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #register,
            [],
            {#user: user},
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> checkAvailableEmail({required String? email}) => (super.noSuchMethod(
        Invocation.method(
          #checkAvailableEmail,
          [],
          {#email: email},
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #checkAvailableEmail,
            [],
            {#email: email},
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #checkAvailableEmail,
            [],
            {#email: email},
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #deleteAccount,
            [],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #deleteAccount,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> get(
    String? endpoint, {
    String? tempHost,
    Map<String, String>? extraHeaders,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
          {
            #tempHost: tempHost,
            #extraHeaders: extraHeaders,
          },
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #get,
            [endpoint],
            {
              #tempHost: tempHost,
              #extraHeaders: extraHeaders,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #get,
            [endpoint],
            {
              #tempHost: tempHost,
              #extraHeaders: extraHeaders,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> post(
    String? endpoint, {
    required dynamic body,
    String? tempHost,
    Map<String, String>? baseHeaders,
    Map<String, String>? extraHeaders,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [endpoint],
          {
            #body: body,
            #tempHost: tempHost,
            #baseHeaders: baseHeaders,
            #extraHeaders: extraHeaders,
          },
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #post,
            [endpoint],
            {
              #body: body,
              #tempHost: tempHost,
              #baseHeaders: baseHeaders,
              #extraHeaders: extraHeaders,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #post,
            [endpoint],
            {
              #body: body,
              #tempHost: tempHost,
              #baseHeaders: baseHeaders,
              #extraHeaders: extraHeaders,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> put(
    String? endpoint, {
    required dynamic body,
    String? tempHost,
    Map<String, String>? extraHeaders,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [endpoint],
          {
            #body: body,
            #tempHost: tempHost,
            #extraHeaders: extraHeaders,
          },
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #put,
            [endpoint],
            {
              #body: body,
              #tempHost: tempHost,
              #extraHeaders: extraHeaders,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #put,
            [endpoint],
            {
              #body: body,
              #tempHost: tempHost,
              #extraHeaders: extraHeaders,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  _i6.Future<_i2.Response> delete(
    String? endpoint, {
    dynamic body,
    String? tempHost,
    Map<String, String>? extraHeaders,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [endpoint],
          {
            #body: body,
            #tempHost: tempHost,
            #extraHeaders: extraHeaders,
          },
        ),
        returnValue: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #delete,
            [endpoint],
            {
              #body: body,
              #tempHost: tempHost,
              #extraHeaders: extraHeaders,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #delete,
            [endpoint],
            {
              #body: body,
              #tempHost: tempHost,
              #extraHeaders: extraHeaders,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response>);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ToastService].
///
/// See the documentation for Mockito's code generation for more information.
class MockToastService extends _i1.Mock implements _i23.ToastService {
  @override
  void showSnackBar({
    String? message,
    _i5.BuildContext? context,
    Duration? duration,
    _i4.Color? textColor,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #showSnackBar,
          [],
          {
            #message: message,
            #context: context,
            #duration: duration,
            #textColor: textColor,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<T> popupMenu<T>(
    _i5.BuildContext? context, {
    required _i4.Color? color,
    required _i24.PopupMenuParameters<dynamic>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #popupMenu,
          [context],
          {
            #color: color,
            #parameters: parameters,
          },
        ),
        returnValue: _i8.ifNotNull(
              _i8.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #popupMenu,
                  [context],
                  {
                    #color: color,
                    #parameters: parameters,
                  },
                ),
              ),
              (T v) => _i6.Future<T>.value(v),
            ) ??
            _FakeFuture_5<T>(
              this,
              Invocation.method(
                #popupMenu,
                [context],
                {
                  #color: color,
                  #parameters: parameters,
                },
              ),
            ),
        returnValueForMissingStub: _i8.ifNotNull(
              _i8.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #popupMenu,
                  [context],
                  {
                    #color: color,
                    #parameters: parameters,
                  },
                ),
              ),
              (T v) => _i6.Future<T>.value(v),
            ) ??
            _FakeFuture_5<T>(
              this,
              Invocation.method(
                #popupMenu,
                [context],
                {
                  #color: color,
                  #parameters: parameters,
                },
              ),
            ),
      ) as _i6.Future<T>);

  @override
  _i6.Future<T> deleteAccountPopupMenu<T>(
    _i5.BuildContext? context, {
    required _i24.PopupMenuParameters<dynamic>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAccountPopupMenu,
          [context],
          {#parameters: parameters},
        ),
        returnValue: _i8.ifNotNull(
              _i8.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #deleteAccountPopupMenu,
                  [context],
                  {#parameters: parameters},
                ),
              ),
              (T v) => _i6.Future<T>.value(v),
            ) ??
            _FakeFuture_5<T>(
              this,
              Invocation.method(
                #deleteAccountPopupMenu,
                [context],
                {#parameters: parameters},
              ),
            ),
        returnValueForMissingStub: _i8.ifNotNull(
              _i8.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #deleteAccountPopupMenu,
                  [context],
                  {#parameters: parameters},
                ),
              ),
              (T v) => _i6.Future<T>.value(v),
            ) ??
            _FakeFuture_5<T>(
              this,
              Invocation.method(
                #deleteAccountPopupMenu,
                [context],
                {#parameters: parameters},
              ),
            ),
      ) as _i6.Future<T>);

  @override
  void unfocusAll(_i5.BuildContext? context) => super.noSuchMethod(
        Invocation.method(
          #unfocusAll,
          [context],
        ),
        returnValueForMissingStub: null,
      );
}
